import { create } from "zustand";
import { persist } from "zustand/middleware";

export type Language = "EN" | "FR" | "DE" | "ES";

export const languageLabels: Record<Language, string> = {
  EN: "English",
  FR: "Français",
  DE: "Deutsch",
  ES: "Español",
};

const translations: Record<Language, Record<string, string>> = {
  EN: {
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.blog": "Blog",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.faq": "FAQ",
    "nav.sell": "Sell With Us",
    "nav.more": "More",
    "banner.free_shipping": "Free shipping on selected orders",
    "hero.title_1": "The Art of the",
    "hero.title_2": "Handmade.",
    "hero.subtitle": "Premium craft supplies, tools, and kits, curated for makers who care about quality, creativity, and ease.",
    "hero.cta": "Start Creating",
    "hero.download": "Download PDF",
    "category.label": "Our Category",
    "category.title_1": "Curated for the",
    "category.title_2": "Maker",
    "yarns.label": "OUR YARNS",
    "yarns.title_1": "All the Yarns You",
    "yarns.title_2": "Love!",
    "yarns.description": "Premium yarns, tools, and kits, curated for crafters who value quality, creativity, and convenience.",
    "yarns.shop_all": "Shop All Yarns",
    "products.add_to_cart": "Add to Cart",
    "products.added": "Added!",
    "products.sale": "Sale",
    "products.shop_all": "Shop All Products",
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.empty_subtitle": "Add something you love and come back here when you're ready.",
    "cart.shop_products": "Shop products",
    "cart.subtotal": "Subtotal",
    "cart.total": "Total",
    "cart.checkout": "Proceed to Checkout",
    "cart.continue": "Continue Shopping",
    "wishlist.title": "Wishlist",
    "wishlist.empty": "Your wishlist is empty",
    "wishlist.empty_subtitle": "Save items you love by clicking the heart on any product.",
    "search.placeholder": "Search products...",
    "search.title": "Search",
    "search.no_results": "No products found",
    "footer.newsletter": "Subscribe to our newsletter",
    "footer.newsletter_placeholder": "Enter your email",
    "footer.subscribe": "Subscribe",
    "footer.company": "Company",
    "footer.support": "Support",
    "footer.shop": "Shop",
    "blog.featured": "Featured Story",
    "blog.latest": "Latest Articles",
    "blog.read": "Read Article",
    "blog.min_read": "min read",
    "blog.no_posts": "No posts yet. Check back soon.",
    "checkout.title": "Checkout",
    "checkout.place_order": "Place Order",
    "checkout.billing": "Billing Details",
    "checkout.shipping": "Shipping",
    "checkout.payment": "Payment",
    "checkout.order_summary": "Order Summary",
    "about.title": "About Us",
    "contact.title": "Contact Us",
    "contact.send": "Send Message",
    "faq.title": "Frequently Asked Questions",
    "sell.title": "Sell With Us",
    "sell.submitted": "Application Submitted!",
    "sell.submitted_subtitle": "Thank you for your interest in selling with us. Our team will review your application and get back to you within 3–5 business days.",
    "sell.submit_another": "Submit another",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.close": "Close",
  },
  FR: {
    "nav.home": "Accueil",
    "nav.shop": "Boutique",
    "nav.blog": "Blog",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.faq": "FAQ",
    "nav.sell": "Vendre avec nous",
    "nav.more": "Plus",
    "banner.free_shipping": "Livraison gratuite sur commandes sélectionnées",
    "hero.title_1": "L'Art du",
    "hero.title_2": "Fait Main.",
    "hero.subtitle": "Fournitures artisanales, outils et kits de qualité, sélectionnés pour les créateurs exigeants.",
    "hero.cta": "Commencer à Créer",
    "hero.download": "Télécharger PDF",
    "category.label": "Nos Catégories",
    "category.title_1": "Sélectionné pour le",
    "category.title_2": "Créateur",
    "yarns.label": "NOS FILS",
    "yarns.title_1": "Tous les Fils que Vous",
    "yarns.title_2": "Aimez !",
    "yarns.description": "Fils, outils et kits de qualité, sélectionnés pour les artisans qui apprécient la qualité, la créativité et la commodité.",
    "yarns.shop_all": "Voir Tous les Fils",
    "products.add_to_cart": "Ajouter au Panier",
    "products.added": "Ajouté !",
    "products.sale": "Promo",
    "products.shop_all": "Voir Tous les Produits",
    "cart.title": "Panier",
    "cart.empty": "Votre panier est vide",
    "cart.empty_subtitle": "Ajoutez quelque chose que vous aimez et revenez quand vous êtes prêt.",
    "cart.shop_products": "Voir les produits",
    "cart.subtotal": "Sous-total",
    "cart.total": "Total",
    "cart.checkout": "Passer à la Caisse",
    "cart.continue": "Continuer les Achats",
    "wishlist.title": "Liste de Souhaits",
    "wishlist.empty": "Votre liste de souhaits est vide",
    "wishlist.empty_subtitle": "Sauvegardez vos articles préférés en cliquant sur le cœur.",
    "search.placeholder": "Rechercher des produits...",
    "search.title": "Recherche",
    "search.no_results": "Aucun produit trouvé",
    "footer.newsletter": "Abonnez-vous à notre newsletter",
    "footer.newsletter_placeholder": "Entrez votre email",
    "footer.subscribe": "S'abonner",
    "footer.company": "Entreprise",
    "footer.support": "Support",
    "footer.shop": "Boutique",
    "blog.featured": "Article Vedette",
    "blog.latest": "Derniers Articles",
    "blog.read": "Lire l'Article",
    "blog.min_read": "min de lecture",
    "blog.no_posts": "Aucun article pour le moment. Revenez bientôt.",
    "checkout.title": "Commande",
    "checkout.place_order": "Passer la Commande",
    "checkout.billing": "Détails de Facturation",
    "checkout.shipping": "Livraison",
    "checkout.payment": "Paiement",
    "checkout.order_summary": "Résumé de la Commande",
    "about.title": "À Propos",
    "contact.title": "Contactez-nous",
    "contact.send": "Envoyer le Message",
    "faq.title": "Questions Fréquentes",
    "sell.title": "Vendre avec Nous",
    "sell.submitted": "Candidature Envoyée !",
    "sell.submitted_subtitle": "Merci pour votre intérêt. Notre équipe examinera votre candidature et vous répondra sous 3 à 5 jours ouvrables.",
    "sell.submit_another": "Soumettre une autre",
    "common.loading": "Chargement...",
    "common.error": "Une erreur est survenue",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.submit": "Soumettre",
    "common.close": "Fermer",
  },
  DE: {
    "nav.home": "Startseite",
    "nav.shop": "Shop",
    "nav.blog": "Blog",
    "nav.about": "Über uns",
    "nav.contact": "Kontakt",
    "nav.faq": "FAQ",
    "nav.sell": "Bei uns verkaufen",
    "nav.more": "Mehr",
    "banner.free_shipping": "Kostenloser Versand bei ausgewählten Bestellungen",
    "hero.title_1": "Die Kunst des",
    "hero.title_2": "Handgemachten.",
    "hero.subtitle": "Hochwertige Bastelmaterialien, Werkzeuge und Sets für kreative Macher.",
    "hero.cta": "Jetzt Starten",
    "hero.download": "PDF Herunterladen",
    "category.label": "Unsere Kategorien",
    "category.title_1": "Kuratiert für den",
    "category.title_2": "Macher",
    "yarns.label": "UNSERE GARNE",
    "yarns.title_1": "Alle Garne, die Sie",
    "yarns.title_2": "Lieben!",
    "yarns.description": "Premium-Garne, Werkzeuge und Sets für Handwerker, die Qualität, Kreativität und Komfort schätzen.",
    "yarns.shop_all": "Alle Garne Ansehen",
    "products.add_to_cart": "In den Warenkorb",
    "products.added": "Hinzugefügt!",
    "products.sale": "Angebot",
    "products.shop_all": "Alle Produkte Ansehen",
    "cart.title": "Warenkorb",
    "cart.empty": "Ihr Warenkorb ist leer",
    "cart.empty_subtitle": "Fügen Sie etwas hinzu, das Ihnen gefällt, und kommen Sie zurück.",
    "cart.shop_products": "Produkte ansehen",
    "cart.subtotal": "Zwischensumme",
    "cart.total": "Gesamt",
    "cart.checkout": "Zur Kasse",
    "cart.continue": "Weiter Einkaufen",
    "wishlist.title": "Wunschliste",
    "wishlist.empty": "Ihre Wunschliste ist leer",
    "wishlist.empty_subtitle": "Speichern Sie Ihre Lieblingsartikel mit einem Klick auf das Herz.",
    "search.placeholder": "Produkte suchen...",
    "search.title": "Suche",
    "search.no_results": "Keine Produkte gefunden",
    "footer.newsletter": "Newsletter abonnieren",
    "footer.newsletter_placeholder": "E-Mail eingeben",
    "footer.subscribe": "Abonnieren",
    "footer.company": "Unternehmen",
    "footer.support": "Support",
    "footer.shop": "Shop",
    "blog.featured": "Empfohlener Artikel",
    "blog.latest": "Neueste Artikel",
    "blog.read": "Artikel Lesen",
    "blog.min_read": "Min. Lesezeit",
    "blog.no_posts": "Noch keine Beiträge. Schauen Sie bald wieder vorbei.",
    "checkout.title": "Bestellung",
    "checkout.place_order": "Bestellung Aufgeben",
    "checkout.billing": "Rechnungsdetails",
    "checkout.shipping": "Versand",
    "checkout.payment": "Zahlung",
    "checkout.order_summary": "Bestellübersicht",
    "about.title": "Über Uns",
    "contact.title": "Kontakt",
    "contact.send": "Nachricht Senden",
    "faq.title": "Häufig Gestellte Fragen",
    "sell.title": "Bei Uns Verkaufen",
    "sell.submitted": "Bewerbung Eingereicht!",
    "sell.submitted_subtitle": "Vielen Dank für Ihr Interesse. Unser Team wird Ihre Bewerbung prüfen und sich innerhalb von 3–5 Werktagen bei Ihnen melden.",
    "sell.submit_another": "Weitere einreichen",
    "common.loading": "Laden...",
    "common.error": "Etwas ist schiefgelaufen",
    "common.back": "Zurück",
    "common.next": "Weiter",
    "common.submit": "Absenden",
    "common.close": "Schließen",
  },
  ES: {
    "nav.home": "Inicio",
    "nav.shop": "Tienda",
    "nav.blog": "Blog",
    "nav.about": "Nosotros",
    "nav.contact": "Contacto",
    "nav.faq": "FAQ",
    "nav.sell": "Vende con Nosotros",
    "nav.more": "Más",
    "banner.free_shipping": "Envío gratuito en pedidos seleccionados",
    "hero.title_1": "El Arte de lo",
    "hero.title_2": "Hecho a Mano.",
    "hero.subtitle": "Materiales artesanales, herramientas y kits de calidad, seleccionados para creadores exigentes.",
    "hero.cta": "Empezar a Crear",
    "hero.download": "Descargar PDF",
    "category.label": "Nuestras Categorías",
    "category.title_1": "Seleccionado para el",
    "category.title_2": "Creador",
    "yarns.label": "NUESTROS HILOS",
    "yarns.title_1": "Todos los Hilos que",
    "yarns.title_2": "¡Amas!",
    "yarns.description": "Hilos, herramientas y kits de calidad, seleccionados para artesanos que valoran la calidad, la creatividad y la comodidad.",
    "yarns.shop_all": "Ver Todos los Hilos",
    "products.add_to_cart": "Añadir al Carrito",
    "products.added": "¡Añadido!",
    "products.sale": "Oferta",
    "products.shop_all": "Ver Todos los Productos",
    "cart.title": "Carrito",
    "cart.empty": "Tu carrito está vacío",
    "cart.empty_subtitle": "Añade algo que te guste y vuelve cuando estés listo.",
    "cart.shop_products": "Ver productos",
    "cart.subtotal": "Subtotal",
    "cart.total": "Total",
    "cart.checkout": "Ir a Pagar",
    "cart.continue": "Seguir Comprando",
    "wishlist.title": "Lista de Deseos",
    "wishlist.empty": "Tu lista de deseos está vacía",
    "wishlist.empty_subtitle": "Guarda tus artículos favoritos haciendo clic en el corazón.",
    "search.placeholder": "Buscar productos...",
    "search.title": "Buscar",
    "search.no_results": "No se encontraron productos",
    "footer.newsletter": "Suscríbete a nuestro boletín",
    "footer.newsletter_placeholder": "Introduce tu email",
    "footer.subscribe": "Suscribirse",
    "footer.company": "Empresa",
    "footer.support": "Soporte",
    "footer.shop": "Tienda",
    "blog.featured": "Artículo Destacado",
    "blog.latest": "Últimos Artículos",
    "blog.read": "Leer Artículo",
    "blog.min_read": "min de lectura",
    "blog.no_posts": "Aún no hay publicaciones. Vuelve pronto.",
    "checkout.title": "Pedido",
    "checkout.place_order": "Realizar Pedido",
    "checkout.billing": "Datos de Facturación",
    "checkout.shipping": "Envío",
    "checkout.payment": "Pago",
    "checkout.order_summary": "Resumen del Pedido",
    "about.title": "Sobre Nosotros",
    "contact.title": "Contáctanos",
    "contact.send": "Enviar Mensaje",
    "faq.title": "Preguntas Frecuentes",
    "sell.title": "Vende con Nosotros",
    "sell.submitted": "¡Solicitud Enviada!",
    "sell.submitted_subtitle": "Gracias por tu interés. Nuestro equipo revisará tu solicitud y te responderá en 3–5 días hábiles.",
    "sell.submit_another": "Enviar otra",
    "common.loading": "Cargando...",
    "common.error": "Algo salió mal",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.submit": "Enviar",
    "common.close": "Cerrar",
  },
};

interface LanguageState {
  language: Language;
  setLanguage: (l: Language) => void;
  t: (key: string) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: "EN",
      setLanguage: (l) => set({ language: l }),
      t: (key: string) => {
        const { language } = get();
        return translations[language]?.[key] ?? translations.EN[key] ?? key;
      },
    }),
    { name: "ecommerce-language" }
  )
);
