import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const categories = [
  { id: "cat-yarn", name: "All Yarns", slug: "all-yarns", image: "/images/categories/all-yarns.svg" },
  { id: "cat-knitting", name: "Knitting", slug: "knitting", image: "/images/categories/knitting.svg" },
  { id: "cat-crochet", name: "Crochet", slug: "crochet", image: "/images/categories/crochet.svg" },
  { id: "cat-embroidery", name: "Embroidery", slug: "embroidery", image: "/images/categories/embroidery.svg" },
  { id: "cat-kits", name: "Craft Kits", slug: "craft-kits", image: "/images/categories/cross-stitch.svg" },
  { id: "cat-tools", name: "Tools & Accessories", slug: "tools-accessories", image: "/images/categories/embroidery-kits.svg" },
  { id: "cat-fabric", name: "Fabric & Fiber", slug: "fabric-fiber", image: "/images/categories/fabric.svg" },
];

const products = [
  {
    id: "prod-1",
    slug: "merino-wool-chunky-rose",
    productCode: "YRN-001",
    name: "Merino Wool Chunky - Dusty Rose",
    priceCents: 1299,
    compareAtCents: 1899,
    rating: 4.8,
    reviewCount: 124,
    images: JSON.stringify(["/images/products/yarn-merino-rose.png"]),
    categoryId: "cat-yarn",
    tags: JSON.stringify(["yarn", "merino", "chunky", "wool"]),
    shortDesc: "Super soft 100% merino wool in a beautiful dusty rose shade. Perfect for cozy scarves, blankets, and winter accessories.",
    longDesc: "Our Merino Wool Chunky is spun from the finest Australian merino fibers, offering exceptional softness and warmth. The dusty rose colorway adds a touch of elegance to any project. This yarn knits up quickly on larger needles and produces a beautiful, lofty fabric with excellent stitch definition.",
    ingredients: "100% Australian Merino Wool",
    howToUse: "Recommended needle size: 6-8mm. Gauge: 12-14 sts per 10cm. Machine wash cold, lay flat to dry.",
    stock: 45,
    badge: "BESTSELLER",
  },
  {
    id: "prod-2",
    slug: "cotton-dk-pastel-collection",
    productCode: "YRN-002",
    name: "Cotton DK Pastel Collection",
    priceCents: 899,
    compareAtCents: null,
    rating: 4.6,
    reviewCount: 89,
    images: JSON.stringify(["/images/products/yarn-cotton-pastels.png"]),
    categoryId: "cat-yarn",
    tags: JSON.stringify(["yarn", "cotton", "dk", "pastel"]),
    shortDesc: "A curated set of soft cotton yarns in dreamy pastel shades. Ideal for baby garments, spring tops, and amigurumi.",
    longDesc: "This beautiful collection includes four coordinating pastel shades of our premium DK weight cotton yarn. Each ball is 50g/125m, giving you plenty to work with. The cotton is mercerized for a subtle sheen and excellent color fastness.",
    ingredients: "100% Mercerized Cotton",
    howToUse: "Recommended needle size: 3.5-4.5mm. Gauge: 22 sts per 10cm. Machine washable at 40°C.",
    stock: 32,
    badge: "NEW",
  },
  {
    id: "prod-3",
    slug: "bamboo-knitting-needles-set",
    productCode: "TLS-001",
    name: "Bamboo Knitting Needles Set",
    priceCents: 2495,
    compareAtCents: 3499,
    rating: 4.9,
    reviewCount: 203,
    images: JSON.stringify(["/images/products/knitting-needles-bamboo.png"]),
    categoryId: "cat-knitting",
    tags: JSON.stringify(["needles", "bamboo", "knitting", "tools"]),
    shortDesc: "Premium bamboo knitting needles in 12 sizes. Smooth finish, lightweight, and gentle on hands.",
    longDesc: "Our bamboo knitting needle set includes 12 pairs of single-pointed needles ranging from 2mm to 10mm. Each pair is 25cm long, crafted from sustainably sourced bamboo with a silky smooth finish that allows stitches to glide effortlessly. The warm feel of bamboo is gentle on arthritic hands and won't slip like metal needles.",
    ingredients: null,
    howToUse: "Includes sizes: 2mm, 2.5mm, 3mm, 3.5mm, 4mm, 4.5mm, 5mm, 5.5mm, 6mm, 7mm, 8mm, 10mm. Comes in a natural cotton roll-up case.",
    stock: 28,
    badge: "BESTSELLER",
  },
  {
    id: "prod-4",
    slug: "amigurumi-animal-crochet-kit",
    productCode: "KIT-001",
    name: "Amigurumi Animal Crochet Kit",
    priceCents: 3299,
    compareAtCents: null,
    rating: 4.7,
    reviewCount: 156,
    images: JSON.stringify(["/images/products/crochet-amigurumi-kit.png"]),
    categoryId: "cat-crochet",
    tags: JSON.stringify(["crochet", "amigurumi", "kit", "beginner"]),
    shortDesc: "Complete kit to crochet adorable stuffed animals. Includes yarn, hooks, stuffing, and step-by-step patterns.",
    longDesc: "Create three adorable amigurumi animals with this all-in-one kit. Includes premium acrylic yarn in 8 colors, a 3.5mm crochet hook, safety eyes, polyester stuffing, yarn needle, and detailed printed patterns with photo tutorials. Perfect for beginners looking to try amigurumi for the first time.",
    ingredients: "Kit includes: 8 yarn balls (acrylic), 3.5mm crochet hook, 12 safety eyes, polyester stuffing, yarn needle, 3 printed patterns",
    howToUse: "Follow the included step-by-step patterns. Suitable for beginners with basic crochet knowledge. Video tutorials available via QR code.",
    stock: 19,
    badge: null,
  },
  {
    id: "prod-5",
    slug: "hand-dyed-sock-yarn-ocean",
    productCode: "YRN-003",
    name: "Hand-Dyed Sock Yarn - Ocean Blues",
    priceCents: 1899,
    compareAtCents: null,
    rating: 4.9,
    reviewCount: 78,
    images: JSON.stringify(["/images/products/yarn-sock-ocean.png"]),
    categoryId: "cat-yarn",
    tags: JSON.stringify(["yarn", "sock", "hand-dyed", "fingering"]),
    shortDesc: "Stunning hand-dyed fingering weight yarn in ocean-inspired blues and teals. Each skein is unique.",
    longDesc: "Our hand-dyed sock yarn is a luxurious blend of superwash merino and nylon for durability. Each skein is individually dyed by hand, creating unique color variations that make every pair of socks one-of-a-kind. The ocean colorway features deep navy, bright teal, and touches of seafoam green.",
    ingredients: "75% Superwash Merino Wool, 25% Nylon",
    howToUse: "Recommended needle size: 2.25-3mm. Gauge: 28-32 sts per 10cm. Machine wash cold on delicate cycle.",
    stock: 15,
    badge: null,
  },
  {
    id: "prod-6",
    slug: "embroidery-starter-kit",
    productCode: "KIT-002",
    name: "Embroidery Starter Kit",
    priceCents: 2199,
    compareAtCents: 2999,
    rating: 4.8,
    reviewCount: 92,
    images: JSON.stringify(["/images/products/embroidery-starter-kit.png"]),
    categoryId: "cat-embroidery",
    tags: JSON.stringify(["embroidery", "starter", "kit", "beginner"]),
    shortDesc: "Everything you need to start embroidering. Includes hoop, floss, needles, fabric, and beginner patterns.",
    longDesc: "Begin your embroidery journey with this comprehensive starter kit. Includes a 6-inch bamboo embroidery hoop, 50 colors of premium embroidery floss, assorted needles, pre-printed cotton fabric with 3 designs, a needle threader, and a detailed instruction booklet covering 15 basic stitches.",
    ingredients: "Kit includes: 6\" bamboo hoop, 50 floss colors, needle set, 3 pre-printed fabrics, instruction booklet, needle threader, scissors",
    howToUse: "Start with the pre-printed designs and follow the stitch guide. Progress to freehand designs as you build confidence.",
    stock: 24,
    badge: "NEW",
  },
  {
    id: "prod-7",
    slug: "alpaca-blend-yarn-oatmeal",
    productCode: "YRN-004",
    name: "Alpaca Blend DK - Natural Oatmeal",
    priceCents: 1599,
    compareAtCents: null,
    rating: 4.7,
    reviewCount: 67,
    images: JSON.stringify(["/images/products/yarn-alpaca-oatmeal.png"]),
    categoryId: "cat-yarn",
    tags: JSON.stringify(["yarn", "alpaca", "dk", "natural"]),
    shortDesc: "Incredibly soft alpaca blend in a neutral oatmeal tone. Warm, lightweight, and hypoallergenic.",
    longDesc: "This DK weight yarn blends baby alpaca with fine merino wool for unmatched softness and warmth without the weight. The natural oatmeal shade is undyed, showcasing the beautiful natural color of the alpaca fiber. Perfect for garments worn close to the skin.",
    ingredients: "70% Baby Alpaca, 30% Merino Wool",
    howToUse: "Recommended needle size: 3.5-4.5mm. Gauge: 22 sts per 10cm. Hand wash cold, reshape and lay flat to dry.",
    stock: 38,
    badge: null,
  },
  {
    id: "prod-8",
    slug: "cross-stitch-floral-kit",
    productCode: "KIT-003",
    name: "Floral Wreath Cross Stitch Kit",
    priceCents: 1899,
    compareAtCents: null,
    rating: 4.6,
    reviewCount: 45,
    images: JSON.stringify(["/images/products/cross-stitch-floral-kit.png"]),
    categoryId: "cat-embroidery",
    tags: JSON.stringify(["cross-stitch", "floral", "kit"]),
    shortDesc: "Create a stunning floral wreath with this complete cross stitch kit. Includes everything you need.",
    longDesc: "This beautiful floral wreath design features roses, lavender, and wildflowers in a circular arrangement. The kit includes 14-count Aida cloth, pre-sorted DMC threads, a tapestry needle, full-color chart, and an 8-inch wooden display hoop. Finished design measures approximately 7 inches in diameter.",
    ingredients: "Kit includes: 14-count Aida cloth, DMC threads, tapestry needle, full-color chart, 8\" display hoop",
    howToUse: "Follow the color-coded chart. Each square on the chart equals one cross stitch. Estimated completion time: 20-30 hours.",
    stock: 22,
    badge: null,
  },
  {
    id: "prod-9",
    slug: "ergonomic-crochet-hooks-set",
    productCode: "TLS-002",
    name: "Ergonomic Crochet Hooks Set",
    priceCents: 1999,
    compareAtCents: 2799,
    rating: 4.8,
    reviewCount: 187,
    images: JSON.stringify(["/images/products/crochet-hooks-ergonomic.png"]),
    categoryId: "cat-crochet",
    tags: JSON.stringify(["crochet", "hooks", "ergonomic", "tools"]),
    shortDesc: "Color-coded ergonomic crochet hooks with soft-grip handles. 9 sizes for comfort and precision.",
    longDesc: "Say goodbye to hand fatigue with our ergonomic crochet hook set. Each hook features an aluminum tip for smooth crocheting and a soft-grip rubber handle that reduces strain during long sessions. The set includes 9 hooks in sizes 2mm to 6mm, each color-coded for easy identification. Comes in a zippered travel case.",
    ingredients: null,
    howToUse: "Sizes included: 2mm, 2.5mm, 3mm, 3.5mm, 4mm, 4.5mm, 5mm, 5.5mm, 6mm. Aluminum tips with TPR rubber handles.",
    stock: 42,
    badge: "BESTSELLER",
  },
  {
    id: "prod-10",
    slug: "mohair-lace-yarn-burgundy",
    productCode: "YRN-005",
    name: "Kid Mohair Lace - Burgundy Wine",
    priceCents: 2199,
    compareAtCents: null,
    rating: 4.5,
    reviewCount: 34,
    images: JSON.stringify(["/images/products/yarn-mohair-burgundy.png"]),
    categoryId: "cat-yarn",
    tags: JSON.stringify(["yarn", "mohair", "lace", "luxury"]),
    shortDesc: "Ethereal kid mohair lace yarn in a deep burgundy. Creates a beautiful halo effect in shawls and scarves.",
    longDesc: "This luxurious lace weight yarn is spun from the finest kid mohair with a touch of silk for added sheen. The burgundy wine colorway is rich and sophisticated, perfect for elegant shawls, lightweight cardigans, and evening accessories. When knitted, the mohair fibers create a beautiful halo effect.",
    ingredients: "72% Kid Mohair, 28% Silk",
    howToUse: "Recommended needle size: 3.5-5mm (for lace work). Gauge varies by pattern. Hand wash gently in lukewarm water.",
    stock: 20,
    badge: null,
  },
  {
    id: "prod-11",
    slug: "punch-needle-rug-kit",
    productCode: "KIT-004",
    name: "Punch Needle Rug Making Kit",
    priceCents: 4499,
    compareAtCents: 5999,
    rating: 4.7,
    reviewCount: 63,
    images: JSON.stringify(["/images/products/punch-needle-kit.png"]),
    categoryId: "cat-kits",
    tags: JSON.stringify(["punch-needle", "rug", "kit"]),
    shortDesc: "Create beautiful punch needle rugs and wall hangings. Complete kit with adjustable needle and premium yarn.",
    longDesc: "Dive into the satisfying world of punch needle with this comprehensive kit. Includes an adjustable punch needle tool (3 loop heights), monks cloth fabric, a wooden frame, and enough chunky acrylic yarn in 6 colors to complete the included geometric pattern. The technique is easy to learn and incredibly relaxing.",
    ingredients: "Kit includes: adjustable punch needle, monks cloth, wooden frame (12\"x12\"), 6 yarn skeins, pattern template, instruction booklet",
    howToUse: "Stretch monks cloth on frame, trace pattern, and punch! Follow the included guide for loop height settings and yarn management tips.",
    stock: 14,
    badge: null,
  },
  {
    id: "prod-12",
    slug: "merino-superwash-forest-green",
    productCode: "YRN-006",
    name: "Superwash Merino Worsted - Forest Green",
    priceCents: 1399,
    compareAtCents: null,
    rating: 4.8,
    reviewCount: 91,
    images: JSON.stringify(["/images/products/yarn-merino-forest.png"]),
    categoryId: "cat-yarn",
    tags: JSON.stringify(["yarn", "merino", "superwash", "worsted"]),
    shortDesc: "Machine-washable merino in a deep forest green. The perfect everyday yarn for garments and accessories.",
    longDesc: "Our superwash merino worsted is the go-to yarn for wearable projects. The superwash treatment means you can machine wash finished items without worry. The deep forest green colorway is versatile and timeless, working beautifully for hats, sweaters, mittens, and blankets.",
    ingredients: "100% Superwash Merino Wool",
    howToUse: "Recommended needle size: 4.5-5.5mm. Gauge: 18-20 sts per 10cm. Machine wash warm, tumble dry low.",
    stock: 55,
    badge: null,
  },
  {
    id: "prod-13",
    slug: "macrame-cord-natural-cotton",
    productCode: "FBR-001",
    name: "Natural Cotton Macramé Cord Bundle",
    priceCents: 2899,
    compareAtCents: 3599,
    rating: 4.6,
    reviewCount: 112,
    images: JSON.stringify(["/images/products/macrame-cord-natural.png"]),
    categoryId: "cat-fabric",
    tags: JSON.stringify(["macrame", "cord", "cotton", "fiber"]),
    shortDesc: "Premium natural cotton macramé cord in 3 thicknesses. Perfect for wall hangings, plant hangers, and home decor.",
    longDesc: "This bundle includes three rolls of unbleached natural cotton macramé cord in 3mm, 5mm, and 7mm thicknesses. Each roll contains 100 meters of cord. The cotton is soft yet sturdy, holds knots well, and frays beautifully for decorative tassels. Ideal for both beginners and experienced macramé artists.",
    ingredients: "100% Natural Unbleached Cotton",
    howToUse: "Use for macramé wall hangings, plant hangers, bag making, and home decor projects. Can be dyed with natural or synthetic dyes.",
    stock: 30,
    badge: null,
  },
  {
    id: "prod-14",
    slug: "weaving-frame-loom-kit",
    productCode: "KIT-005",
    name: "Frame Loom Weaving Starter Kit",
    priceCents: 3999,
    compareAtCents: null,
    rating: 4.5,
    reviewCount: 48,
    images: JSON.stringify(["/images/products/weaving-loom-kit.png"]),
    categoryId: "cat-kits",
    tags: JSON.stringify(["weaving", "loom", "kit", "beginner"]),
    shortDesc: "Learn to weave with this complete frame loom kit. Includes loom, tools, yarn, and step-by-step guide.",
    longDesc: "This beautiful handcrafted wooden frame loom measures 12\" x 16\" and comes with everything you need to start weaving. The kit includes a shed stick, tapestry shuttle, weaving comb, cotton warp thread, and a curated selection of yarns in coordinating colors for your first project. The detailed instruction booklet covers plain weave, rya knots, and soumak techniques.",
    ingredients: "Kit includes: 12\"x16\" beech wood frame loom, shed stick, shuttle, comb, warp thread, 8 yarn varieties, needle, instruction booklet",
    howToUse: "Warp your loom following the guide, then weave! Start with plain weave and progress to textured techniques. Suitable for complete beginners.",
    stock: 11,
    badge: "NEW",
  },
  {
    id: "prod-15",
    slug: "cotton-dk-coral-red",
    productCode: "YRN-007",
    name: "Paintbox Cotton DK - Coral Red",
    priceCents: 499,
    compareAtCents: 750,
    rating: 4.4,
    reviewCount: 215,
    images: JSON.stringify(["/images/products/yarn-dk-coral.png", "/images/products/cotton-dk-gallery-1.webp", "/images/products/cotton-dk-gallery-2.webp", "/images/products/cotton-dk-gallery-3.webp", "/images/products/cotton-dk-gallery-4.webp"]),
    categoryId: "cat-yarn",
    tags: JSON.stringify(["yarn", "cotton", "dk", "coral"]),
    shortDesc: "Bright and cheerful cotton DK in a vivid coral red. Great for summer tops, bags, and home accessories.",
    longDesc: "Paintbox Cotton DK is a reliable, affordable cotton yarn loved by makers worldwide. This coral red shade is vibrant and eye-catching, perfect for summer garments, market bags, dishcloths, and colorful amigurumi. The yarn has a slight twist that provides excellent stitch definition and minimal splitting.",
    ingredients: "100% Cotton",
    howToUse: "Recommended needle size: 3.5-4.5mm / hook: 4mm. Gauge: 22 sts per 10cm. Machine wash at 40°C.",
    stock: 80,
    badge: null,
  },
  {
    id: "prod-16",
    slug: "needle-felting-starter-kit",
    productCode: "KIT-006",
    name: "Needle Felting Starter Kit",
    priceCents: 2699,
    compareAtCents: null,
    rating: 4.7,
    reviewCount: 73,
    images: JSON.stringify(["/images/products/felting-needle-kit.png"]),
    categoryId: "cat-kits",
    tags: JSON.stringify(["felting", "needle", "kit", "wool"]),
    shortDesc: "Everything to start needle felting. Includes rainbow wool roving, felting needles, and foam pad.",
    longDesc: "Explore the art of needle felting with this complete starter kit. Includes 20 colors of premium wool roving, 6 felting needles in 3 gauges (fine, medium, coarse), a high-density foam felting pad, finger guards, and a 40-page project booklet with instructions for making adorable miniature animals and decorations.",
    ingredients: "Kit includes: 20 colors wool roving (5g each), 6 felting needles, foam pad, finger guards, project booklet, storage case",
    howToUse: "Place roving on foam pad and repeatedly poke with felting needle to sculpt shapes. Start with simple forms and progress to detailed figures. Always use on foam pad to protect needle tips.",
    stock: 26,
    badge: null,
  },
];

const variations = [
  {
    productId: "prod-1",
    attributes: [
      {
        name: "Weight",
        values: JSON.stringify(["Chunky", "Super Chunky", "Bulky"]),
        displayType: "button",
        displayData: JSON.stringify(null),
      },
      {
        name: "Color",
        values: JSON.stringify(["Dusty Rose", "Ivory", "Sage", "Charcoal"]),
        displayType: "swatch",
        displayData: JSON.stringify({
          "Dusty Rose": "#C9A4A0",
          "Ivory": "#F5F0E8",
          "Sage": "#A8B5A0",
          "Charcoal": "#4A4A4A",
        }),
      },
    ],
    variations: [
      { attributes: JSON.stringify({ Weight: "Chunky", Color: "Dusty Rose" }), stock: 15, sku: "YRN-001-CHK-DR" },
      { attributes: JSON.stringify({ Weight: "Chunky", Color: "Ivory" }), stock: 12, sku: "YRN-001-CHK-IV" },
      { attributes: JSON.stringify({ Weight: "Chunky", Color: "Sage" }), stock: 8, sku: "YRN-001-CHK-SG" },
      { attributes: JSON.stringify({ Weight: "Chunky", Color: "Charcoal" }), stock: 10, sku: "YRN-001-CHK-CH" },
      { attributes: JSON.stringify({ Weight: "Super Chunky", Color: "Dusty Rose" }), stock: 6, sku: "YRN-001-SCH-DR" },
      { attributes: JSON.stringify({ Weight: "Super Chunky", Color: "Ivory" }), stock: 5, sku: "YRN-001-SCH-IV" },
    ],
  },
  {
    productId: "prod-3",
    attributes: [
      {
        name: "Type",
        values: JSON.stringify(["Single Pointed", "Circular", "Double Pointed"]),
        displayType: "button",
        displayData: JSON.stringify(null),
      },
    ],
    variations: [
      { attributes: JSON.stringify({ Type: "Single Pointed" }), stock: 12, sku: "TLS-001-SP" },
      { attributes: JSON.stringify({ Type: "Circular" }), stock: 8, sku: "TLS-001-CIR" },
      { attributes: JSON.stringify({ Type: "Double Pointed" }), stock: 8, sku: "TLS-001-DP" },
    ],
  },
  {
    productId: "prod-5",
    attributes: [
      {
        name: "Colorway",
        values: JSON.stringify(["Ocean Blues", "Sunset Reds", "Forest Walk", "Lavender Fields"]),
        displayType: "swatch",
        displayData: JSON.stringify({
          "Ocean Blues": "#2E7D9B",
          "Sunset Reds": "#C44D3F",
          "Forest Walk": "#4A7C5B",
          "Lavender Fields": "#9B7CB8",
        }),
      },
    ],
    variations: [
      { attributes: JSON.stringify({ Colorway: "Ocean Blues" }), stock: 5, sku: "YRN-003-OB" },
      { attributes: JSON.stringify({ Colorway: "Sunset Reds" }), stock: 4, sku: "YRN-003-SR" },
      { attributes: JSON.stringify({ Colorway: "Forest Walk" }), stock: 3, sku: "YRN-003-FW" },
      { attributes: JSON.stringify({ Colorway: "Lavender Fields" }), stock: 3, sku: "YRN-003-LF" },
    ],
  },
  {
    productId: "prod-9",
    attributes: [
      {
        name: "Set Size",
        values: JSON.stringify(["9-Piece Standard", "14-Piece Complete"]),
        displayType: "button",
        displayData: JSON.stringify(null),
      },
    ],
    variations: [
      { attributes: JSON.stringify({ "Set Size": "9-Piece Standard" }), stock: 25, sku: "TLS-002-9PC", priceCents: 1999 },
      { attributes: JSON.stringify({ "Set Size": "14-Piece Complete" }), stock: 17, sku: "TLS-002-14PC", priceCents: 2999 },
    ],
  },
  {
    productId: "prod-12",
    attributes: [
      {
        name: "Color",
        values: JSON.stringify(["Forest Green", "Navy Blue", "Mustard", "Berry", "Natural"]),
        displayType: "swatch",
        displayData: JSON.stringify({
          "Forest Green": "#2D5A3D",
          "Navy Blue": "#1E3A5F",
          "Mustard": "#D4A547",
          "Berry": "#8B2252",
          "Natural": "#E8DFD0",
        }),
      },
    ],
    variations: [
      { attributes: JSON.stringify({ Color: "Forest Green" }), stock: 15, sku: "YRN-006-FG" },
      { attributes: JSON.stringify({ Color: "Navy Blue" }), stock: 12, sku: "YRN-006-NB" },
      { attributes: JSON.stringify({ Color: "Mustard" }), stock: 10, sku: "YRN-006-MS" },
      { attributes: JSON.stringify({ Color: "Berry" }), stock: 8, sku: "YRN-006-BR" },
      { attributes: JSON.stringify({ Color: "Natural" }), stock: 10, sku: "YRN-006-NT" },
    ],
  },
  {
    productId: "prod-15",
    attributes: [
      {
        name: "Color",
        values: JSON.stringify(["Coral Red", "Sunflower", "Sky Blue", "Mint", "Blush Pink", "Pure White"]),
        displayType: "swatch",
        displayData: JSON.stringify({
          "Coral Red": "#E05A47",
          "Sunflower": "#F5C842",
          "Sky Blue": "#6EB5D9",
          "Mint": "#A8D8B9",
          "Blush Pink": "#F0C4C4",
          "Pure White": "#FFFFFF",
        }),
      },
    ],
    variations: [
      { attributes: JSON.stringify({ Color: "Coral Red" }), stock: 20, sku: "YRN-007-CR" },
      { attributes: JSON.stringify({ Color: "Sunflower" }), stock: 15, sku: "YRN-007-SF" },
      { attributes: JSON.stringify({ Color: "Sky Blue" }), stock: 18, sku: "YRN-007-SB" },
      { attributes: JSON.stringify({ Color: "Mint" }), stock: 12, sku: "YRN-007-MT" },
      { attributes: JSON.stringify({ Color: "Blush Pink" }), stock: 10, sku: "YRN-007-BP" },
      { attributes: JSON.stringify({ Color: "Pure White" }), stock: 5, sku: "YRN-007-PW" },
    ],
  },
];

async function main() {
  for (const cat of categories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, image: cat.image },
      create: cat,
    });
  }
  console.log(`Seeded ${categories.length} categories`);

  for (const prod of products) {
    await prisma.product.upsert({
      where: { slug: prod.slug },
      update: {
        name: prod.name,
        priceCents: prod.priceCents,
        compareAtCents: prod.compareAtCents,
        images: prod.images,
        categoryId: prod.categoryId,
        tags: prod.tags,
        shortDesc: prod.shortDesc,
        longDesc: prod.longDesc,
        stock: prod.stock,
        badge: prod.badge,
        rating: prod.rating,
        reviewCount: prod.reviewCount,
      },
      create: prod,
    });
  }
  console.log(`Seeded ${products.length} products`);

  for (const v of variations) {
    await prisma.productAttribute.deleteMany({
      where: { productId: v.productId },
    });
    await prisma.productVariation.deleteMany({
      where: { productId: v.productId },
    });

    for (const attr of v.attributes) {
      await prisma.productAttribute.create({
        data: {
          productId: v.productId,
          name: attr.name,
          values: attr.values,
          displayType: attr.displayType,
          displayData: attr.displayData,
        },
      });
    }

    for (const vari of v.variations) {
      await prisma.productVariation.create({
        data: {
          productId: v.productId,
          attributes: vari.attributes,
          stock: vari.stock,
          sku: vari.sku,
          priceCents: (vari as any).priceCents ?? null,
        },
      });
    }
  }
  console.log(`Seeded variations for ${variations.length} products`);
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
